changelog:
  categories:
    - title: 🚀 New Features
      labels: [enhancement]
    - title: 🐛 Bug Fixes
      labels: [bug]
    - title: 🛠 Refactoring
      labels: [refactoring]
    - title: ⚡ Performance
      labels: [performance]
    - title: 🧪 Tests
      labels: [testing]
    - title: ⚙️ CI/CD
      labels: [ci-cd]
    - title: 📚 Documentation
      labels: [documentation]
    - title: 📦 Dependencies
      labels: [dependencies]
    - title: Other Changes
      labels: ['*']
